config/routes.rb
Todo::Application.routes.draw do
  resources :tasks, except: :index
  
  root 'pages#home'
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :note
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @tasks = Task.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :note, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Todo
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      .hero-unit.text-center
        %h1
          To Do
        %p 
        = link_to 'New Task', new_task_path, class: 'btn btn-primary', remote: true      
    = yield

app/views/pages/home.html.haml
.container
  - if @tasks.empty?
    %span.text-warning There are no tasks!
  - else
    %table.table.table-hover.table-bordered
      %thead
        %tr
          %th Title
          %th Created
          %th Completed
      %tbody
        - @tasks.each do |task|
          %tr
            %td
              %strong= task.title
            %td.text-info= task.created_at
            %td.text-success= task.completed
#modal.modal.fade

app/views/tasks/_form.html.haml
.modal-header
  %h1 Create a New Task
= simple_form_for task, class: 'clearfix' do |f|
  .modal-body
    = f.input :title
    = f.input :note
    = f.input :completed, as: :string, input_html: {class: 'datepicker'}
  .modal-footer
    = f.submit 'Save', class: 'btn btn-success'

app/views/tasks/new.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'form', locals: {task: @task} ) %>');
m.modal('show');
$('#modal').integrateDatepicker();